// Generated by gencpp from file multi_orbbec/GetBool.msg
// DO NOT EDIT!


#ifndef MULTI_ORBBEC_MESSAGE_GETBOOL_H
#define MULTI_ORBBEC_MESSAGE_GETBOOL_H

#include <ros/service_traits.h>


#include <multi_orbbec/GetBoolRequest.h>
#include <multi_orbbec/GetBoolResponse.h>


namespace multi_orbbec
{

struct GetBool
{

typedef GetBoolRequest Request;
typedef GetBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBool
} // namespace multi_orbbec


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::multi_orbbec::GetBool > {
  static const char* value()
  {
    return "43f76a855b16e988566e147b692f2fab";
  }

  static const char* value(const ::multi_orbbec::GetBool&) { return value(); }
};

template<>
struct DataType< ::multi_orbbec::GetBool > {
  static const char* value()
  {
    return "multi_orbbec/GetBool";
  }

  static const char* value(const ::multi_orbbec::GetBool&) { return value(); }
};


// service_traits::MD5Sum< ::multi_orbbec::GetBoolRequest> should match
// service_traits::MD5Sum< ::multi_orbbec::GetBool >
template<>
struct MD5Sum< ::multi_orbbec::GetBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::multi_orbbec::GetBool >::value();
  }
  static const char* value(const ::multi_orbbec::GetBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_orbbec::GetBoolRequest> should match
// service_traits::DataType< ::multi_orbbec::GetBool >
template<>
struct DataType< ::multi_orbbec::GetBoolRequest>
{
  static const char* value()
  {
    return DataType< ::multi_orbbec::GetBool >::value();
  }
  static const char* value(const ::multi_orbbec::GetBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::multi_orbbec::GetBoolResponse> should match
// service_traits::MD5Sum< ::multi_orbbec::GetBool >
template<>
struct MD5Sum< ::multi_orbbec::GetBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::multi_orbbec::GetBool >::value();
  }
  static const char* value(const ::multi_orbbec::GetBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_orbbec::GetBoolResponse> should match
// service_traits::DataType< ::multi_orbbec::GetBool >
template<>
struct DataType< ::multi_orbbec::GetBoolResponse>
{
  static const char* value()
  {
    return DataType< ::multi_orbbec::GetBool >::value();
  }
  static const char* value(const ::multi_orbbec::GetBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MULTI_ORBBEC_MESSAGE_GETBOOL_H
