// Generated by gencpp from file multi_orbbec/GetCameraParams.msg
// DO NOT EDIT!


#ifndef MULTI_ORBBEC_MESSAGE_GETCAMERAPARAMS_H
#define MULTI_ORBBEC_MESSAGE_GETCAMERAPARAMS_H

#include <ros/service_traits.h>


#include <multi_orbbec/GetCameraParamsRequest.h>
#include <multi_orbbec/GetCameraParamsResponse.h>


namespace multi_orbbec
{

struct GetCameraParams
{

typedef GetCameraParamsRequest Request;
typedef GetCameraParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCameraParams
} // namespace multi_orbbec


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::multi_orbbec::GetCameraParams > {
  static const char* value()
  {
    return "06621ca772ba4ac96475002c209b1554";
  }

  static const char* value(const ::multi_orbbec::GetCameraParams&) { return value(); }
};

template<>
struct DataType< ::multi_orbbec::GetCameraParams > {
  static const char* value()
  {
    return "multi_orbbec/GetCameraParams";
  }

  static const char* value(const ::multi_orbbec::GetCameraParams&) { return value(); }
};


// service_traits::MD5Sum< ::multi_orbbec::GetCameraParamsRequest> should match
// service_traits::MD5Sum< ::multi_orbbec::GetCameraParams >
template<>
struct MD5Sum< ::multi_orbbec::GetCameraParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::multi_orbbec::GetCameraParams >::value();
  }
  static const char* value(const ::multi_orbbec::GetCameraParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_orbbec::GetCameraParamsRequest> should match
// service_traits::DataType< ::multi_orbbec::GetCameraParams >
template<>
struct DataType< ::multi_orbbec::GetCameraParamsRequest>
{
  static const char* value()
  {
    return DataType< ::multi_orbbec::GetCameraParams >::value();
  }
  static const char* value(const ::multi_orbbec::GetCameraParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::multi_orbbec::GetCameraParamsResponse> should match
// service_traits::MD5Sum< ::multi_orbbec::GetCameraParams >
template<>
struct MD5Sum< ::multi_orbbec::GetCameraParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::multi_orbbec::GetCameraParams >::value();
  }
  static const char* value(const ::multi_orbbec::GetCameraParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_orbbec::GetCameraParamsResponse> should match
// service_traits::DataType< ::multi_orbbec::GetCameraParams >
template<>
struct DataType< ::multi_orbbec::GetCameraParamsResponse>
{
  static const char* value()
  {
    return DataType< ::multi_orbbec::GetCameraParams >::value();
  }
  static const char* value(const ::multi_orbbec::GetCameraParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MULTI_ORBBEC_MESSAGE_GETCAMERAPARAMS_H
