// Generated by gencpp from file multi_orbbec/GetString.msg
// DO NOT EDIT!


#ifndef MULTI_ORBBEC_MESSAGE_GETSTRING_H
#define MULTI_ORBBEC_MESSAGE_GETSTRING_H

#include <ros/service_traits.h>


#include <multi_orbbec/GetStringRequest.h>
#include <multi_orbbec/GetStringResponse.h>


namespace multi_orbbec
{

struct GetString
{

typedef GetStringRequest Request;
typedef GetStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetString
} // namespace multi_orbbec


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::multi_orbbec::GetString > {
  static const char* value()
  {
    return "15baad3d82a7b70bfc4eb31d66322293";
  }

  static const char* value(const ::multi_orbbec::GetString&) { return value(); }
};

template<>
struct DataType< ::multi_orbbec::GetString > {
  static const char* value()
  {
    return "multi_orbbec/GetString";
  }

  static const char* value(const ::multi_orbbec::GetString&) { return value(); }
};


// service_traits::MD5Sum< ::multi_orbbec::GetStringRequest> should match
// service_traits::MD5Sum< ::multi_orbbec::GetString >
template<>
struct MD5Sum< ::multi_orbbec::GetStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::multi_orbbec::GetString >::value();
  }
  static const char* value(const ::multi_orbbec::GetStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_orbbec::GetStringRequest> should match
// service_traits::DataType< ::multi_orbbec::GetString >
template<>
struct DataType< ::multi_orbbec::GetStringRequest>
{
  static const char* value()
  {
    return DataType< ::multi_orbbec::GetString >::value();
  }
  static const char* value(const ::multi_orbbec::GetStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::multi_orbbec::GetStringResponse> should match
// service_traits::MD5Sum< ::multi_orbbec::GetString >
template<>
struct MD5Sum< ::multi_orbbec::GetStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::multi_orbbec::GetString >::value();
  }
  static const char* value(const ::multi_orbbec::GetStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_orbbec::GetStringResponse> should match
// service_traits::DataType< ::multi_orbbec::GetString >
template<>
struct DataType< ::multi_orbbec::GetStringResponse>
{
  static const char* value()
  {
    return DataType< ::multi_orbbec::GetString >::value();
  }
  static const char* value(const ::multi_orbbec::GetStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MULTI_ORBBEC_MESSAGE_GETSTRING_H
