// Generated by gencpp from file multi_orbbec/SetString.msg
// DO NOT EDIT!


#ifndef MULTI_ORBBEC_MESSAGE_SETSTRING_H
#define MULTI_ORBBEC_MESSAGE_SETSTRING_H

#include <ros/service_traits.h>


#include <multi_orbbec/SetStringRequest.h>
#include <multi_orbbec/SetStringResponse.h>


namespace multi_orbbec
{

struct SetString
{

typedef SetStringRequest Request;
typedef SetStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetString
} // namespace multi_orbbec


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::multi_orbbec::SetString > {
  static const char* value()
  {
    return "546971982e3fbbd5a41e60fb6432e357";
  }

  static const char* value(const ::multi_orbbec::SetString&) { return value(); }
};

template<>
struct DataType< ::multi_orbbec::SetString > {
  static const char* value()
  {
    return "multi_orbbec/SetString";
  }

  static const char* value(const ::multi_orbbec::SetString&) { return value(); }
};


// service_traits::MD5Sum< ::multi_orbbec::SetStringRequest> should match
// service_traits::MD5Sum< ::multi_orbbec::SetString >
template<>
struct MD5Sum< ::multi_orbbec::SetStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::multi_orbbec::SetString >::value();
  }
  static const char* value(const ::multi_orbbec::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_orbbec::SetStringRequest> should match
// service_traits::DataType< ::multi_orbbec::SetString >
template<>
struct DataType< ::multi_orbbec::SetStringRequest>
{
  static const char* value()
  {
    return DataType< ::multi_orbbec::SetString >::value();
  }
  static const char* value(const ::multi_orbbec::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::multi_orbbec::SetStringResponse> should match
// service_traits::MD5Sum< ::multi_orbbec::SetString >
template<>
struct MD5Sum< ::multi_orbbec::SetStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::multi_orbbec::SetString >::value();
  }
  static const char* value(const ::multi_orbbec::SetStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_orbbec::SetStringResponse> should match
// service_traits::DataType< ::multi_orbbec::SetString >
template<>
struct DataType< ::multi_orbbec::SetStringResponse>
{
  static const char* value()
  {
    return DataType< ::multi_orbbec::SetString >::value();
  }
  static const char* value(const ::multi_orbbec::SetStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MULTI_ORBBEC_MESSAGE_SETSTRING_H
