// Generated by gencpp from file multi_launch/GetBool.msg
// DO NOT EDIT!


#ifndef MULTI_LAUNCH_MESSAGE_GETBOOL_H
#define MULTI_LAUNCH_MESSAGE_GETBOOL_H

#include <ros/service_traits.h>


#include <multi_launch/GetBoolRequest.h>
#include <multi_launch/GetBoolResponse.h>


namespace multi_launch
{

struct GetBool
{

typedef GetBoolRequest Request;
typedef GetBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBool
} // namespace multi_launch


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::multi_launch::GetBool > {
  static const char* value()
  {
    return "43f76a855b16e988566e147b692f2fab";
  }

  static const char* value(const ::multi_launch::GetBool&) { return value(); }
};

template<>
struct DataType< ::multi_launch::GetBool > {
  static const char* value()
  {
    return "multi_launch/GetBool";
  }

  static const char* value(const ::multi_launch::GetBool&) { return value(); }
};


// service_traits::MD5Sum< ::multi_launch::GetBoolRequest> should match
// service_traits::MD5Sum< ::multi_launch::GetBool >
template<>
struct MD5Sum< ::multi_launch::GetBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::multi_launch::GetBool >::value();
  }
  static const char* value(const ::multi_launch::GetBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_launch::GetBoolRequest> should match
// service_traits::DataType< ::multi_launch::GetBool >
template<>
struct DataType< ::multi_launch::GetBoolRequest>
{
  static const char* value()
  {
    return DataType< ::multi_launch::GetBool >::value();
  }
  static const char* value(const ::multi_launch::GetBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::multi_launch::GetBoolResponse> should match
// service_traits::MD5Sum< ::multi_launch::GetBool >
template<>
struct MD5Sum< ::multi_launch::GetBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::multi_launch::GetBool >::value();
  }
  static const char* value(const ::multi_launch::GetBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_launch::GetBoolResponse> should match
// service_traits::DataType< ::multi_launch::GetBool >
template<>
struct DataType< ::multi_launch::GetBoolResponse>
{
  static const char* value()
  {
    return DataType< ::multi_launch::GetBool >::value();
  }
  static const char* value(const ::multi_launch::GetBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MULTI_LAUNCH_MESSAGE_GETBOOL_H
