// Generated by gencpp from file multi_launch/GetDeviceInfoRequest.msg
// DO NOT EDIT!


#ifndef MULTI_LAUNCH_MESSAGE_GETDEVICEINFOREQUEST_H
#define MULTI_LAUNCH_MESSAGE_GETDEVICEINFOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace multi_launch
{
template <class ContainerAllocator>
struct GetDeviceInfoRequest_
{
  typedef GetDeviceInfoRequest_<ContainerAllocator> Type;

  GetDeviceInfoRequest_()
    {
    }
  GetDeviceInfoRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::multi_launch::GetDeviceInfoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multi_launch::GetDeviceInfoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetDeviceInfoRequest_

typedef ::multi_launch::GetDeviceInfoRequest_<std::allocator<void> > GetDeviceInfoRequest;

typedef boost::shared_ptr< ::multi_launch::GetDeviceInfoRequest > GetDeviceInfoRequestPtr;
typedef boost::shared_ptr< ::multi_launch::GetDeviceInfoRequest const> GetDeviceInfoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multi_launch::GetDeviceInfoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multi_launch::GetDeviceInfoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace multi_launch

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::multi_launch::GetDeviceInfoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_launch::GetDeviceInfoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_launch::GetDeviceInfoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_launch::GetDeviceInfoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_launch::GetDeviceInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_launch::GetDeviceInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multi_launch::GetDeviceInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::multi_launch::GetDeviceInfoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::multi_launch::GetDeviceInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multi_launch/GetDeviceInfoRequest";
  }

  static const char* value(const ::multi_launch::GetDeviceInfoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multi_launch::GetDeviceInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::multi_launch::GetDeviceInfoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multi_launch::GetDeviceInfoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetDeviceInfoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multi_launch::GetDeviceInfoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::multi_launch::GetDeviceInfoRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MULTI_LAUNCH_MESSAGE_GETDEVICEINFOREQUEST_H
