// Generated by gencpp from file multi_launch/GetDeviceInfo.msg
// DO NOT EDIT!


#ifndef MULTI_LAUNCH_MESSAGE_GETDEVICEINFO_H
#define MULTI_LAUNCH_MESSAGE_GETDEVICEINFO_H

#include <ros/service_traits.h>


#include <multi_launch/GetDeviceInfoRequest.h>
#include <multi_launch/GetDeviceInfoResponse.h>


namespace multi_launch
{

struct GetDeviceInfo
{

typedef GetDeviceInfoRequest Request;
typedef GetDeviceInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDeviceInfo
} // namespace multi_launch


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::multi_launch::GetDeviceInfo > {
  static const char* value()
  {
    return "a172c842ade7825e92d115b1aef6b0d1";
  }

  static const char* value(const ::multi_launch::GetDeviceInfo&) { return value(); }
};

template<>
struct DataType< ::multi_launch::GetDeviceInfo > {
  static const char* value()
  {
    return "multi_launch/GetDeviceInfo";
  }

  static const char* value(const ::multi_launch::GetDeviceInfo&) { return value(); }
};


// service_traits::MD5Sum< ::multi_launch::GetDeviceInfoRequest> should match
// service_traits::MD5Sum< ::multi_launch::GetDeviceInfo >
template<>
struct MD5Sum< ::multi_launch::GetDeviceInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::multi_launch::GetDeviceInfo >::value();
  }
  static const char* value(const ::multi_launch::GetDeviceInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_launch::GetDeviceInfoRequest> should match
// service_traits::DataType< ::multi_launch::GetDeviceInfo >
template<>
struct DataType< ::multi_launch::GetDeviceInfoRequest>
{
  static const char* value()
  {
    return DataType< ::multi_launch::GetDeviceInfo >::value();
  }
  static const char* value(const ::multi_launch::GetDeviceInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::multi_launch::GetDeviceInfoResponse> should match
// service_traits::MD5Sum< ::multi_launch::GetDeviceInfo >
template<>
struct MD5Sum< ::multi_launch::GetDeviceInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::multi_launch::GetDeviceInfo >::value();
  }
  static const char* value(const ::multi_launch::GetDeviceInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_launch::GetDeviceInfoResponse> should match
// service_traits::DataType< ::multi_launch::GetDeviceInfo >
template<>
struct DataType< ::multi_launch::GetDeviceInfoResponse>
{
  static const char* value()
  {
    return DataType< ::multi_launch::GetDeviceInfo >::value();
  }
  static const char* value(const ::multi_launch::GetDeviceInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MULTI_LAUNCH_MESSAGE_GETDEVICEINFO_H
