// Generated by gencpp from file multi_launch/GetInt32.msg
// DO NOT EDIT!


#ifndef MULTI_LAUNCH_MESSAGE_GETINT32_H
#define MULTI_LAUNCH_MESSAGE_GETINT32_H

#include <ros/service_traits.h>


#include <multi_launch/GetInt32Request.h>
#include <multi_launch/GetInt32Response.h>


namespace multi_launch
{

struct GetInt32
{

typedef GetInt32Request Request;
typedef GetInt32Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetInt32
} // namespace multi_launch


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::multi_launch::GetInt32 > {
  static const char* value()
  {
    return "1e06c77f31583d55c01571a573d75b9f";
  }

  static const char* value(const ::multi_launch::GetInt32&) { return value(); }
};

template<>
struct DataType< ::multi_launch::GetInt32 > {
  static const char* value()
  {
    return "multi_launch/GetInt32";
  }

  static const char* value(const ::multi_launch::GetInt32&) { return value(); }
};


// service_traits::MD5Sum< ::multi_launch::GetInt32Request> should match
// service_traits::MD5Sum< ::multi_launch::GetInt32 >
template<>
struct MD5Sum< ::multi_launch::GetInt32Request>
{
  static const char* value()
  {
    return MD5Sum< ::multi_launch::GetInt32 >::value();
  }
  static const char* value(const ::multi_launch::GetInt32Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_launch::GetInt32Request> should match
// service_traits::DataType< ::multi_launch::GetInt32 >
template<>
struct DataType< ::multi_launch::GetInt32Request>
{
  static const char* value()
  {
    return DataType< ::multi_launch::GetInt32 >::value();
  }
  static const char* value(const ::multi_launch::GetInt32Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::multi_launch::GetInt32Response> should match
// service_traits::MD5Sum< ::multi_launch::GetInt32 >
template<>
struct MD5Sum< ::multi_launch::GetInt32Response>
{
  static const char* value()
  {
    return MD5Sum< ::multi_launch::GetInt32 >::value();
  }
  static const char* value(const ::multi_launch::GetInt32Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_launch::GetInt32Response> should match
// service_traits::DataType< ::multi_launch::GetInt32 >
template<>
struct DataType< ::multi_launch::GetInt32Response>
{
  static const char* value()
  {
    return DataType< ::multi_launch::GetInt32 >::value();
  }
  static const char* value(const ::multi_launch::GetInt32Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MULTI_LAUNCH_MESSAGE_GETINT32_H
