// Generated by gencpp from file multi_launch/GetString.msg
// DO NOT EDIT!


#ifndef MULTI_LAUNCH_MESSAGE_GETSTRING_H
#define MULTI_LAUNCH_MESSAGE_GETSTRING_H

#include <ros/service_traits.h>


#include <multi_launch/GetStringRequest.h>
#include <multi_launch/GetStringResponse.h>


namespace multi_launch
{

struct GetString
{

typedef GetStringRequest Request;
typedef GetStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetString
} // namespace multi_launch


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::multi_launch::GetString > {
  static const char* value()
  {
    return "15baad3d82a7b70bfc4eb31d66322293";
  }

  static const char* value(const ::multi_launch::GetString&) { return value(); }
};

template<>
struct DataType< ::multi_launch::GetString > {
  static const char* value()
  {
    return "multi_launch/GetString";
  }

  static const char* value(const ::multi_launch::GetString&) { return value(); }
};


// service_traits::MD5Sum< ::multi_launch::GetStringRequest> should match
// service_traits::MD5Sum< ::multi_launch::GetString >
template<>
struct MD5Sum< ::multi_launch::GetStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::multi_launch::GetString >::value();
  }
  static const char* value(const ::multi_launch::GetStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_launch::GetStringRequest> should match
// service_traits::DataType< ::multi_launch::GetString >
template<>
struct DataType< ::multi_launch::GetStringRequest>
{
  static const char* value()
  {
    return DataType< ::multi_launch::GetString >::value();
  }
  static const char* value(const ::multi_launch::GetStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::multi_launch::GetStringResponse> should match
// service_traits::MD5Sum< ::multi_launch::GetString >
template<>
struct MD5Sum< ::multi_launch::GetStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::multi_launch::GetString >::value();
  }
  static const char* value(const ::multi_launch::GetStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_launch::GetStringResponse> should match
// service_traits::DataType< ::multi_launch::GetString >
template<>
struct DataType< ::multi_launch::GetStringResponse>
{
  static const char* value()
  {
    return DataType< ::multi_launch::GetString >::value();
  }
  static const char* value(const ::multi_launch::GetStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MULTI_LAUNCH_MESSAGE_GETSTRING_H
