// Generated by gencpp from file multi_launch/SetBool.msg
// DO NOT EDIT!


#ifndef MULTI_LAUNCH_MESSAGE_SETBOOL_H
#define MULTI_LAUNCH_MESSAGE_SETBOOL_H

#include <ros/service_traits.h>


#include <multi_launch/SetBoolRequest.h>
#include <multi_launch/SetBoolResponse.h>


namespace multi_launch
{

struct SetBool
{

typedef SetBoolRequest Request;
typedef SetBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetBool
} // namespace multi_launch


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::multi_launch::SetBool > {
  static const char* value()
  {
    return "09fb03525b03e7ea1fd3992bafd87e16";
  }

  static const char* value(const ::multi_launch::SetBool&) { return value(); }
};

template<>
struct DataType< ::multi_launch::SetBool > {
  static const char* value()
  {
    return "multi_launch/SetBool";
  }

  static const char* value(const ::multi_launch::SetBool&) { return value(); }
};


// service_traits::MD5Sum< ::multi_launch::SetBoolRequest> should match
// service_traits::MD5Sum< ::multi_launch::SetBool >
template<>
struct MD5Sum< ::multi_launch::SetBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::multi_launch::SetBool >::value();
  }
  static const char* value(const ::multi_launch::SetBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_launch::SetBoolRequest> should match
// service_traits::DataType< ::multi_launch::SetBool >
template<>
struct DataType< ::multi_launch::SetBoolRequest>
{
  static const char* value()
  {
    return DataType< ::multi_launch::SetBool >::value();
  }
  static const char* value(const ::multi_launch::SetBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::multi_launch::SetBoolResponse> should match
// service_traits::MD5Sum< ::multi_launch::SetBool >
template<>
struct MD5Sum< ::multi_launch::SetBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::multi_launch::SetBool >::value();
  }
  static const char* value(const ::multi_launch::SetBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_launch::SetBoolResponse> should match
// service_traits::DataType< ::multi_launch::SetBool >
template<>
struct DataType< ::multi_launch::SetBoolResponse>
{
  static const char* value()
  {
    return DataType< ::multi_launch::SetBool >::value();
  }
  static const char* value(const ::multi_launch::SetBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MULTI_LAUNCH_MESSAGE_SETBOOL_H
