// Generated by gencpp from file multi_launch/SetString.msg
// DO NOT EDIT!


#ifndef MULTI_LAUNCH_MESSAGE_SETSTRING_H
#define MULTI_LAUNCH_MESSAGE_SETSTRING_H

#include <ros/service_traits.h>


#include <multi_launch/SetStringRequest.h>
#include <multi_launch/SetStringResponse.h>


namespace multi_launch
{

struct SetString
{

typedef SetStringRequest Request;
typedef SetStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetString
} // namespace multi_launch


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::multi_launch::SetString > {
  static const char* value()
  {
    return "546971982e3fbbd5a41e60fb6432e357";
  }

  static const char* value(const ::multi_launch::SetString&) { return value(); }
};

template<>
struct DataType< ::multi_launch::SetString > {
  static const char* value()
  {
    return "multi_launch/SetString";
  }

  static const char* value(const ::multi_launch::SetString&) { return value(); }
};


// service_traits::MD5Sum< ::multi_launch::SetStringRequest> should match
// service_traits::MD5Sum< ::multi_launch::SetString >
template<>
struct MD5Sum< ::multi_launch::SetStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::multi_launch::SetString >::value();
  }
  static const char* value(const ::multi_launch::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_launch::SetStringRequest> should match
// service_traits::DataType< ::multi_launch::SetString >
template<>
struct DataType< ::multi_launch::SetStringRequest>
{
  static const char* value()
  {
    return DataType< ::multi_launch::SetString >::value();
  }
  static const char* value(const ::multi_launch::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::multi_launch::SetStringResponse> should match
// service_traits::MD5Sum< ::multi_launch::SetString >
template<>
struct MD5Sum< ::multi_launch::SetStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::multi_launch::SetString >::value();
  }
  static const char* value(const ::multi_launch::SetStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_launch::SetStringResponse> should match
// service_traits::DataType< ::multi_launch::SetString >
template<>
struct DataType< ::multi_launch::SetStringResponse>
{
  static const char* value()
  {
    return DataType< ::multi_launch::SetString >::value();
  }
  static const char* value(const ::multi_launch::SetStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MULTI_LAUNCH_MESSAGE_SETSTRING_H
